source 'https://gems.ruby-china.com'

gem 'rails'
gem 'sqlite3','~>1.3.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '>= 0.4.0', group: :doc
gem 'tzinfo-data'
gem 'tzinfo'



