version: '3'
services:
        db:
          image: postgres
          volumes:
            - ./tmp/db:/var/lib/postgresql/data
        rails:
          build: ./rails
          command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
          volumes:
            - ./rails:/myapp
          ports:
            - "3000:3000"
          depends_on:
            - db
        web:
          build: ./nginx
          volumes:
            - ./tmp/nginx_root:/usr/share/nginx/html
          ports:
            - "8080:80"
          depends_on:
            - rails

                  

