version: '3'
services:
  apt-cacher-ng:
    restart: always
    build: ./apt-cacher-ng
    ports:
        - 3142:3142
    volumes:
      - ./data:/var/cache/apt-cacher-ng
      - ./log:/var/log/apt-cacher-ng
