version: '3'

services:
  etcd_1:  
    image:  quay.io/coreos/etcd
    volumes:
        - "./data_etcd1/:/etcd.etcd/"
    environment:
      ETCD_NAME: etcd_1
      ETCDCTL_API: 3
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_1:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_1:2380
      ETCD_INITIAL_CLUSTER_TOKEN:  etcd-cluster-1
      ETCD_INITIAL_CLUSTER: etcd_1=http://etcd_1:2380,etcd_2=http://etcd_2:2380,etcd_3=http://etcd_3:2380
      ETCD_INITIAL_CLUSTER_STATE: new

  etcd_2:
    image: quay.io/coreos/etcd
    volumes:
        - "./data_etcd2/:/etcd.etcd/"
    environment:
      ETCD_NAME: etcd_2
      ETCDCTL_API: 3
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_2:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_2:2380
      ETCD_INITIAL_CLUSTER_TOKEN:  etcd-cluster-1
      ETCD_INITIAL_CLUSTER: etcd_1=http://etcd_1:2380,etcd_2=http://etcd_2:2380,etcd_3=http://etcd_3:2380
      ETCD_INITIAL_CLUSTER_STATE: new

  etcd_3:
    image: quay.io/coreos/etcd    
    volumes:
        - "./data_etcd3/:/etcd.etcd/"
    environment:
      ETCD_NAME: etcd_3
      ETCDCTL_API: 3
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_3:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd_3:2380
      ETCD_INITIAL_CLUSTER_TOKEN:  etcd-cluster-1
      ETCD_INITIAL_CLUSTER: etcd_1=http://etcd_1:2380,etcd_2=http://etcd_2:2380,etcd_3=http://etcd_3:2380
      ETCD_INITIAL_CLUSTER_STATE: new

  etcd_4:
    image: quay.io/coreos/etcd 
    volumes:
        - "./data_etcd4/:/etcd.etcd/"
    environment:
      ETCDCTL_API: 3
      ETCD_NAME: etcd_4
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_4:2379
      ETCD_INITIAL_CLUSTER: "etcd_1=http://etcd_1:2380,etcd_2=http://etcd_2:2380,etcd_3=http://etcd_3:2380,etcd_4=http://etcd_4:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd_4:2380"
      ETCD_INITIAL_CLUSTER_STATE: "existing"

      

  etcd_5:
    image: quay.io/coreos/etcd 
    volumes:
        - "./data_etcd5/:/etcd.etcd/"
    environment:
      ETCDCTL_API: 3
      ETCD_NAME: etcd_5
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd_5:2379
      ETCD_INITIAL_CLUSTER: "etcd_1=http://etcd_1:2380,etcd_2=http://etcd_2:2380,etcd_3=http://etcd_3:2380,etcd_4=http://etcd_4:2380,,etcd_5=http://etcd_5:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd_5:2380"
      ETCD_INITIAL_CLUSTER_STATE: "existing"


  ruby:
    image: ruby
    volumes:
      - "./script/:/script/"
    working_dir: "/script/"
    

    
