version: '3'

services:
  etcd_1:
    image: elcolio/etcd
    volumes:
      - "/data_etcd1/:/data/"
    command:
      - "--name infra0"
      - "--listen-client-urls http://0.0.0.0:12379"
      - "--advertise-client-urls http://0.0.0.0:12379"
      - "--listen-peer-urls http://0.0.0.0:12380"
      - "--initial-advertise-peer-urls http://0.0.0.0:12380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster 'infra0=http://0.0.0.0:12380'"
      - "--initial-cluster-state new"
