version: '3'

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -  subnet: "172.16.238.0/24"
services:
  etcd_1:
    image: elcolio/etcd
    networks:
      app_net:
        ipv4_address: "172.16.238.11"
    volumes:
        - "./data_etcd1/:/data/"
    command:
      - "--name etcd_1"
      - "--listen-client-urls http://0.0.0.0:2379"
      - "--advertise-client-urls http://172.16.238.11:2379"
      - "--listen-peer-urls http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls http://172.16.238.11:2380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster etcd_1=http://172.16.238.11:2380,etcd_2=http://172.16.238.12:2380,etcd_3=http://172.16.238.13:2380,etcd_4=http://172.16.238.14:2380,etcd_5=http://172.16.238.15:2380,etcd_6=http://172.16.238.16:2380"
      - "--initial-cluster-state new"  
  etcd_2:
    image: elcolio/etcd
    networks:
      app_net:
        ipv4_address: "172.16.238.12"
    volumes:
        - "./data_etcd2/:/data/"
    command:
      - "--name etcd_2"
      - "--listen-client-urls http://0.0.0.0:2379"
      - "--advertise-client-urls http://172.16.238.12:2379"
      - "--listen-peer-urls http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls http://172.16.238.12:2380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster etcd_1=http://172.16.238.11:2380,etcd_2=http://172.16.238.12:2380,etcd_3=http://172.16.238.13:2380,etcd_4=http://172.16.238.14:2380,etcd_5=http://172.16.238.15:2380,etcd_6=http://172.16.238.16:2380"
      - "--initial-cluster-state new"
  etcd_3:
    image: elcolio/etcd
    networks:
      app_net:
        ipv4_address: "172.16.238.13"
    volumes:
        - "./data_etcd3/:/data/"
    command:
      - "--name etcd_3"
      - "--listen-client-urls http://0.0.0.0:2379"
      - "--advertise-client-urls http://172.16.238.13:2379"
      - "--listen-peer-urls http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls http://172.16.238.13:2380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster etcd_1=http://172.16.238.11:2380,etcd_2=http://172.16.238.12:2380,etcd_3=http://172.16.238.13:2380,etcd_4=http://172.16.238.14:2380,etcd_5=http://172.16.238.15:2380,etcd_6=http://172.16.238.16:2380"
      - "--initial-cluster-state new"
  etcd_4:
    image: elcolio/etcd
    networks:
      app_net:
        ipv4_address: "172.16.238.14"
    volumes:
        - "./data_etcd4/:/data/"
    command:
      - "--name etcd_4"
      - "--listen-client-urls http://0.0.0.0:2379"
      - "--advertise-client-urls http://172.16.238.14:2379"
      - "--listen-peer-urls http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls http://172.16.238.14:2380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster etcd_1=http://172.16.238.11:2380,etcd_2=http://172.16.238.12:2380,etcd_3=http://172.16.238.13:2380,etcd_4=http://172.16.238.14:2380,etcd_5=http://172.16.238.15:2380,etcd_6=http://172.16.238.16:2380"
      - "--initial-cluster-state new"
  etcd_5:
    image: elcolio/etcd
    networks:
      app_net:
        ipv4_address: "172.16.238.15"
    volumes:
        - "./data_etcd5/:/data/"
    command:
      - "--name etcd_5"
      - "--listen-client-urls http://0.0.0.0:2379"
      - "--advertise-client-urls http://172.16.238.15:2379"
      - "--listen-peer-urls http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls http://172.16.238.15:2380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster etcd_1=http://172.16.238.11:2380,etcd_2=http://172.16.238.12:2380,etcd_3=http://172.16.238.13:2380,etcd_4=http://172.16.238.14:2380,etcd_5=http://172.16.238.15:2380,etcd_6=http://172.16.238.16:2380"
      - "--initial-cluster-state new"

  etcd_6:
    image: elcolio/etcd
    networks:
      app_net:
        ipv4_address: "172.16.238.16"
    volumes:
        - "./data_etcd6/:/data/"
    command:
      - "--name etcd_6"
      - "--listen-client-urls http://0.0.0.0:2379"
      - "--advertise-client-urls http://172.16.238.16:2379"
      - "--listen-peer-urls http://0.0.0.0:2380"
      - "--initial-advertise-peer-urls http://172.16.238.16:2380"
      - "--initial-cluster-token etcd-cluster-1"
      - "--initial-cluster etcd_1=http://172.16.238.11:2380,etcd_2=http://172.16.238.12:2380,etcd_3=http://172.16.238.13:2380,etcd_4=http://172.16.238.14:2380,etcd_5=http://172.16.238.15:2380,etcd_6=http://172.16.238.16:2380"
      - "--initial-cluster-state new"


